using osu.Framework.Localisation;
using osucc.Localisation;

namespace MyPlugin;

/// <summary>String keys for the plugin, resolved from the embedded Localisation JSON (follows the osu! language).</summary>
public static class MyPluginStrings
{
    private const string prefix = "my-plugin";

    private static string getKey(string name) => $"{prefix}:{name}";

    public static LocalisableString Name => OsuCcLocalisation.Get($"{prefix}:name", "My Plugin");

    public static LocalisableString Description => OsuCcLocalisation.Get($"{prefix}:description", "An osu-cc plugin generated by dotnet new osucc-plugin.");

    public static LocalisableString TooltipMain => OsuCcLocalisation.Get(getKey(nameof(TooltipMain)), "My plugin");

    public static LocalisableString TooltipSub => OsuCcLocalisation.Get(getKey(nameof(TooltipSub)), "Sends a notification");

    public static LocalisableString HelloNotification => OsuCcLocalisation.Get(getKey(nameof(HelloNotification)), "Hello from MyPlugin!");

    public static LocalisableString EnabledCaption => OsuCcLocalisation.Get(getKey(nameof(EnabledCaption)), "Enabled");

    public static LocalisableString EnabledHint => OsuCcLocalisation.Get(getKey(nameof(EnabledHint)), "Whether the plugin is active.");
}
