using osucc.Plugin;

namespace MyPlugin;

/// <summary>
/// Minimal osu-cc plugin: registers a toolbar button and a settings subsection (persisted via
/// <see cref="PluginSettings"/>). Builds to <c>bin/&lt;config&gt;/net8.0/MyPlugin.zip</c>;
/// drop that archive into the game's <c>osu-cc/plugins</c> folder.
/// Dependencies on other plugins are declared via <c>DependsOn</c> (e.g.
/// <c>DependsOn = new[] { "other-plugin-id" }</c>) — see the ExamplePlugin for a full walkthrough.
/// </summary>
[OsuCcPlugin("my-plugin", "My Plugin", 100, Author = "you", Description = "An osu-cc plugin generated by dotnet new osucc-plugin.", Version = "1.0.0")]
public class MyPlugin : OsuCcPluginBase
{
    private PluginSettings settings = null!;

    protected override void OnLoad()
    {
        settings = Host.GetSettings();

        Host.AddToolbarButton(() => new MyToolbarButton(Host.Notify));
        Host.AddSettingsSubsection(() => new MySettingsSubsection(settings));

        Host.Log("loaded");
    }

    public override void Dispose()
    {
        GC.SuppressFinalize(this);
        settings?.Dispose();
        base.Dispose();
    }
}
