<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SubdivideNations</AssemblyName>
    <RootNamespace>SubdivideNations</RootNamespace>
    <IsPlugin>true</IsPlugin>
    <PackageId>subdivide-nations</PackageId>
    <Title>Subdivide Nations</Title>
    <Description>Shows each user's sub-national region on profiles and user cards.</Description>
    <Version>1.0.1</Version>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/RuJect/osu-cc</RepositoryUrl>
    <PackageTags>profile;region</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Author Include="rus07tam" OsuProfileId="33701908" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Api" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Regions.json" />
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>
