<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>osuccDebug</AssemblyName>
    <RootNamespace>osuccDebug</RootNamespace>
    <IsPlugin>true</IsPlugin>
    <PluginId>osucc-debug</PluginId>
    <PluginName>Debug Overlay</PluginName>
    <PluginDescription>The debug overlay: customised test overlays and notifications.</PluginDescription>
    <PluginVersion>1.0.1</PluginVersion>
    <PluginIconGlyph>Bug</PluginIconGlyph>
    <PluginRepository>https://github.com/RuJect/osu-cc</PluginRepository>
  </PropertyGroup>

  <ItemGroup>
    <PluginAuthor Include="rus07tam" OsuProfileId="33701908" />
    <PluginTag Include="debug" />
    <PluginTag Include="dev" />
    <PluginTag Include="tools" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Host" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>
