<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>osuccDebug</AssemblyName>
    <RootNamespace>osuccDebug</RootNamespace>
    <IsPlugin>true</IsPlugin>
    <PackageId>osucc-debug</PackageId>
    <Title>Debug Overlay</Title>
    <Description>The debug overlay: customised test overlays and notifications.</Description>
    <Version>1.0.1</Version>
    <IconGlyph>Bug</IconGlyph>
    <RepositoryUrl>https://github.com/RuJect/osu-cc</RepositoryUrl>
    <PackageTags>debug;dev;tools</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Author Include="rus07tam" OsuProfileId="33701908" />
  </ItemGroup>

  <ItemGroup>
    <PluginDocument Include="README.md" Title="README" IconGlyph="Book" />
    <PluginDocument Include="CHANGELOG.md" Title="Changelog" IconGlyph="History" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Api" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>
