<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Oii</AssemblyName>
    <RootNamespace>Oii</RootNamespace>
    <IsPlugin>true</IsPlugin>
    <PluginId>oii</PluginId>
    <PluginName>oii</PluginName>
    <PluginDescription>Shows the improvement indicator next to total play time on user profiles.</PluginDescription>
    <PluginVersion>1.0.1</PluginVersion>
    <PluginIcon>icon.png</PluginIcon>
    <PluginRepository>https://github.com/RuJect/osu-cc</PluginRepository>
  </PropertyGroup>

  <ItemGroup>
    <PluginAuthor Include="rus07tam" OsuProfileId="33701908" />
    <PluginTag Include="profile" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Host" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>
