<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FriendsLeaderboard</AssemblyName>
    <RootNamespace>FriendsLeaderboard</RootNamespace>
    <IsPlugin>true</IsPlugin>
    <PackageId>friends-leaderboard</PackageId>
    <Title>Friends Leaderboard</Title>
    <Description>Shows the friend leaderboard without an osu!supporter tag by aggregating each
      friend's best score client-side.</Description>
    <Version>1.0.1</Version>
    <RepositoryUrl>https://github.com/RuJect/osu-cc</RepositoryUrl>
    <PackageTags>leaderboard</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Author Include="rus07tam" OsuProfileId="33701908" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Api" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>
