<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FriendsLeaderboard</AssemblyName>
    <RootNamespace>FriendsLeaderboard</RootNamespace>
    <IsPlugin>true</IsPlugin>
    <PluginId>friends-leaderboard</PluginId>
    <PluginName>Friends Leaderboard</PluginName>
    <PluginDescription>Shows the friend leaderboard without an osu!supporter tag by aggregating each
      friend's best score client-side.</PluginDescription>
    <PluginVersion>1.0.0</PluginVersion>
  </PropertyGroup>

  <ItemGroup>
    <PluginAuthor Include="rus07tam" OsuProfileId="33701908" />
    <PluginTag Include="leaderboard" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Host" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>
