<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ExamplePlugin</AssemblyName>
    <RootNamespace>ExamplePlugin</RootNamespace>
    <IsPlugin>true</IsPlugin>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Host" />
    <PackageReference Include="osucc.Build" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" />
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localisation/*.json" />
  </ItemGroup>

</Project>