<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>$(OsuCcLauncherVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\osucc.Shared\osucc.Shared.csproj" />
  </ItemGroup>
</Project>
